/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/settings/About.vue')['default']
    Appearance: typeof import('./src/components/settings/Appearance.vue')['default']
    ArrayInput: typeof import('./src/components/ArrayInput.vue')['default']
    ArraySelect: typeof import('./src/components/ArraySelect.vue')['default']
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next')['BButtonGroup']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTable: typeof import('bootstrap-vue-next')['BTable']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    CredentialManager: typeof import('./src/components/git/CredentialManager.vue')['default']
    General: typeof import('./src/components/settings/General.vue')['default']
    HiddenInput: typeof import('./src/components/HiddenInput.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NetworkInput: typeof import('./src/components/NetworkInput.vue')['default']
    RepositoryList: typeof import('./src/components/git/RepositoryList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Security: typeof import('./src/components/settings/Security.vue')['default']
    StackList: typeof import('./src/components/StackList.vue')['default']
    StackListItem: typeof import('./src/components/StackListItem.vue')['default']
    Terminal: typeof import('./src/components/Terminal.vue')['default']
    TwoFADialog: typeof import('./src/components/TwoFADialog.vue')['default']
    Uptime: typeof import('./src/components/Uptime.vue')['default']
  }
}
